import type { Metadata } from "next";
import "../css/globals.css";
import { ReduxProvider } from "@/redux/provider";
import { interFont } from "@/utils/font";
import { PrimeReactProvider } from 'primereact/api';


export const metadata: Metadata = {
  title: "LLI Indonesia",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <PrimeReactProvider>
        <html lang="en">
          <body >
            <div className={` ${interFont.className} dark:bg-boxdark-2 dark:text-bodydark`}>
              {children}
            </div>
          </body>
        </html>
      </PrimeReactProvider>
    </ReduxProvider>
  );
}
